#!/usr/local/bin/zsh

typeset -U ruby_version
ruby_version="$(cat ~/.dotfiles/ruby/ruby-version.symlink)"
rbenv shell $ruby_version
unset ruby_version

cat ~/.dotfiles/packages/ruby | xargs gem install
