#!/usr/bin/env bash
#
# Run all dotfiles installers.

DOTFILES_ROOT="`pwd`"
set -e

# cd "$(dirname $)"/..

# find the installers and run them iteratively
# find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
find $DOTFILES_ROOT -name install.sh | while read installer ; do sh -c "${installer}" ; done
