name: "default"
windows:
  - name: "services"
    root: "~/code/"
    layout: tiled
    panes:
      - commands:
        - cowsay "Starting your_app"
      - cd ~/code/
  - name: "code"
    root: "~/code/"
    panes:
      - ls
  - name: "chats"
    root: "~"
    panes:
      - irc
