#!/usr/bin/env bash

if [ "$(uname -s)" == "Darwin" ]
then
  set -e

  cd "$(dirname "$0")"

  export HOMEBREW_CASK_OPTS="--appdir=/Applications"

  echo "checking for existing homebrew install"

  if test ! $(which brew)
  then
    echo "existing install not found, installing homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    echo "installed homebrew"
  fi

  echo "updating homebrew"

  sudo xcodebuild -license accept
  brew update

  echo "updated homebrew"


  echo "installing homebrew bundler"

  ln -sfv ~/.dotfiles/homebrew/Brewfile ~/Brewfile

  brew tap homebrew/bundle
  brew bundle --file=~/Brewfile
  sudo xcodebuild -license accept

  echo "finished homebrew setup"
fi
