#!/usr/bin/env bash

if [ "$(uname -s)" == "Darwin" ]
then
  set -e

  cd "$(dirname "$0")"

  export HOMEBREW_CASK_OPTS="--appdir=/Applications"

  echo "checking for existing homebrew install"

  if test ! $(which brew)
  then
    echo "existing install not found, installing homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    echo "installed homebrew"
  fi

  echo "updating homebrew"

  brew update

  echo "updated homebrew"


  echo "installing homebrew bundler"

  ln -sfv $HOME/.dotfiles/homebrew/Brewfile $HOME/Brewfile

  brew tap homebrew/bundle
  brew bundle --file=$HOME/Brewfile

  echo "finished homebrew setup"
fi
