#!/bin/zsh

echo '

   ┌┬┐┌─┐┌─┐┌─┐┬  ┬┌┬┐┬ ┬┬┌─┐
   │││├┤ │ ┬├─┤│  │ │ ├─┤││   :: DOTFILES
   ┴ ┴└─┘└─┘┴ ┴┴─┘┴ ┴ ┴ ┴┴└─┘
   Brought to you by: Seth Messer / @megalithic

Setting up dotfiles. If the ~/.dotfiles folder does not exist, it will be cloned
down from https://github.com/megalithic/dotfiles. The ZShell configuration uses the
Prezto framework, which will be installed or updated at this time.
'

# Run all installers and symlink dotfiles

if [[ "$(uname -s)" != "Darwin" ]]
then
  echo "this installer only runs on macOS; aborting."
  exit 1
fi

if [[ "$(which git)" == "" ]]
then
  echo "this installer needs git"
  echo "do you want to install xcode ?"
  read answer
  if [[ $answer != [yY] ]]
  then
    exit 0
  fi

  echo "installing xcode"
  xcode-select --install
  # exit 0
fi

# set -e

echo "::beginning the dotfiling.."

# Setup
if [[ -z $HOMEDIR ]]
then
  export HOMEDIR=$HOME
fi

if [[ -z $DOTS ]]
then
  export DOTDIR="$HOMEDIR/.dotfiles"
  # export DOTS="$DOTDIR/config"
fi

if [[ ! -d $DOTDIR ]]
then
  echo "Cloning dotfiles..."
  mkdir -p $DOTDIR
  git clone --recursive git://github.com/megalithic/dotfiles.git "$DOTDIR"
else
  if [[ -z $SKIP_DOTFILES_UPDATE ]]
  then
    cd $DOTDIR
    git add -u .
    git stash
    git pull --recurse-submodules --rebase origin master
    git push origin master
    git stash pop
    cd $HOMEDIR
  fi
fi

# app/system installers
scripts/homebrew

# TODO: get these working again, but take care of order of things
# scripts/generic
# scripts/platform

# setup all zsh things
sh zsh/install.sh

# node packages and versions
sh node/install.sh

# ruby packages and versions
sh ruby/install.sh

# python packages and versions
sh python/install.sh

# nvim plugins
sh nvim/install.sh

# tmux plugins
sh tmux/install.sh

# terminfo configuration
sh terminfo/install.sh

# macOS defaults changes and tweaks
sh osx/install.sh

# symlink all the things to all their places
scripts/symlinks

# keyboard/karabiner specific configurations
sh keyboard/install.sh

# setup private repo things for secretz
scripts/private
