#!/bin/zsh

if [ "$(uname -s)" == "Darwin" ]
then
  export HOMEBREW_CASK_OPTS="--appdir=/Applications"

  echo "checking for existing homebrew install"

  # Install Homebrew and Brews
  if ! type "brew" > /dev/null; then
    echo "Installing Homebrew..."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  echo "Brewing applications..."
  brew update
  brew bundle --file=$DOTDIR/homebrew/Brewfile
  if [[ -a $DOTDIR/homebrew/Brewfile.local ]]
  then
    brew bundle --file=$DOTS/homebrew/Brewfile.local
  fi

  sudo xcodebuild -license accept

  ln -sfv /usr/local/bin/gcc-4.9 /usr/local/bin/gcc

  echo "finished homebrew setup"
fi
