#!/usr/bin/env bash
#
# Links *.symlink to $HOME/*.foo

DOTFILES_ROOT="`pwd`"

set -e

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

symlink_files () {
	info 'symlinking dotfiles'
  echo ''

	for found in **/*.symlink; do
		source="$HOME/.dotfiles/$found"
    dest="$HOME/.`basename \"${found%.*}\"`"

    if [ -f $dest ] || [ -d $dest ]; then
      rm -rf $dest
      success "removed $dest"
    fi

		ln -sf $source $dest
		success "symlinked $source to $dest"
	done
}

symlink_files
