#!/usr/bin/zsh

symlink_files () {
	echo 'symlinking dotfiles...'
  echo '-------------------'

	for found in **/*.symlink; do
		source="$DOTDIR/$found"
    dest="$HOME/.`basename \"${found%.*}\"`"

    if [ -f $dest ] || [ -d $dest ]; then
      rm -rf $dest
      echo "removed $dest"
    fi

		ln -sf $source $dest
		echo "symlinked $source to $dest"
	done
}

symlink_files
