# Default Theme

if patched_font_in_use; then
  TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="\|" #⮂
  TMUX_POWERLINE_SEPARATOR_LEFT_THIN="▮" #⮃
  TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="\|" #⮀
  TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="▮" #◊⮁
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR:-'234'}
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR=${TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR:-'235'}
TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=${TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR:-$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}


# Format: segment_name background_color foreground_color [non_default_separator]

if [ -z $TMUX_POWERLINE_LEFT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
		# "hostname 33 0" \
    "tmux_session_info 234 138 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}" \
		"lan_ip 234 136 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}" \
		"wan_ip 234 136 ${TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD}" \
	)
fi

if [ -z $TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS ]; then
	TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
		# "now_playing 234 37 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		"weather 234 136 ${TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}" \
    # "ifstat 234 137 ${TMUX_POWERLINE_SEPARATOR_LEFT_BOLD}" \
    # "ifstat_sys 234 137 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		"battery 234 136 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		"date_day 234 138 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		"date 234 138 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
		"time 234 138 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}" \
	)
fi
